<?php
/**
* English file for plugin djg_google_xml_sitemaps
*
* @package wolf
* @subpackage djg_google_xml_sitemaps
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast 
*
**/
return array(
/** DjgGoogleXmlSitemapsController.php */ 
'Cache was cleared.' => 'Cache wurde gelöscht.',
'Successfully added file(s)' => 'Erfolgreich Datei (en)',
'Successfully removed file(s)' => 'Erfolgreich entfernt Datei (en)',
'The settings have been updated.' => 'Die Einstellungen wurden aktualisiert.',
/** enable.php */ 
'djg_google_xml_sitemaps - plugin settings initialized.' => 'djg_google_xml_sitemaps - Plugin-Einstellungen initialisiert.',
'djg_google_xml_sitemaps - unable to store plugin settings!' => 'djg_google_xml_sitemaps - keine Plugin-Einstellungen zu speichern!',
/** index.php */ 
'[djg] XML sitemaps' => '[Djg] XML-Sitemaps',
'Simple plugin to generate xml sitemap SEO compatible.' => 'Einfache Plugin, um XML-Sitemap-SEO kompatibel zu generieren.',
'Changefreq' => 'Changefreq',
'always' => 'immer',
'hourly' => 'stündlich',
'daily' => 'täglich',
'weekly' => 'wöchentlich',
'monthly' => 'monatlich',
'yearly' => 'jährlich',
'never' => 'nie',
'Priority' => 'Priorität',
/** views\css_files.php */ 
'CSS files' => 'CSS-Dateien',
'List css files from public/themes directory' => 'Liste css-Dateien von öffentlichen / themes-Verzeichnis',
'All available files are in use' => 'Alle verfügbaren Dateien verwendet werden',
'add selected' => 'Hinzufügen ausgewählt',
'Files in use' => 'Dateien im Einsatz',
'No files' => 'Keine Dateien',
'remove selected' => 'entfernen ausgewählt',
'Show css content' => 'Css Inhalt anzeigen',
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'Sie haben diese Seite modifiziert.  Wenn Sie sich von dieser Seite zu navigieren, ohne zuerst das Speichern Ihrer Daten, werden die Änderungen verloren.',
'Updated file list' => 'Aktualisiert Dateiliste',
/** views\documentation.php */ 
'Documentation' => 'Dokumentation',
/** views\settings.php */ 
'Settings' => 'Einstellungen',
'Header' => 'Kopfzeile',
'XML' => 'XML',
'TXT' => 'TXT',
'Choose header.' => 'Wählen Sie Kopfzeile.',
'HOMEPAGE' => 'STARTSEITE',
'Yes' => 'Ja',
'No' => 'Nicht',
'Add HOMEPAGE to xml tree.' => 'STARTSEITE hinzufügen, um XML-Struktur.',
'STATUS HIDDEN' => 'Status verborgen',
'Add HIDDEN PAGES to xml tree.' => 'In HIDDEN SEITEN, um XML-Baum.',
'LOGIN REQUIRED' => 'Anmeldung erforderlich',
'Add LOGIN REQUIRED PAGES to xml tree.' => 'In Anmeldung erforderlich SEITEN, um XML-Baum.',
'Default changefreq for pages.' => 'Standard changefreq für Seiten.',
'Default priority for pages.' => 'Standard-Priorität für die Seiten.',
'Cache' => 'Cache-Speicher',
'Set Yes if you want to caching sitemap file.' => 'Stellen Sie Ja, wenn Sie Sitemap-Datei zwischenspeichern möchten.',
'Auto clean cache after page update' => 'Auto sauber Cache nach Update-Seite',
'Robots.txt' => 'Robots.txt',
'Contents of the robots.txt file.' => 'Inhalt der robots.txt-Datei.',
'Virtual css path' => 'Virtuelle css-Pfad',
'Save' => 'Sparen',
'Show sitemap.xml file' => 'Sitemap.xml Datei anzeigen',
'Show robots.txt file' => 'Robots.txt-Datei anzeigen',
/** views\sidebar.php */ 
'CSS' => 'CSS',
'Clear cache (:date)' => 'USUN Cache (: date)',
'Documentation' => 'Dokumentacja',
);