<?php
/**
* English file for plugin djg_google_xml_sitemaps
*
* @package wolf
* @subpackage djg_google_xml_sitemaps
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast <djgprv@gmail.com>
*
**/
return array(
/** DjgGoogleXmlSitemapsController.php */ 
'Cache was cleared.' => 'Cache was cleared.', 
'Successfully added file(s)' => 'Successfully added file(s)', 
'Successfully removed file(s)' => 'Successfully removed file(s)', 
'The settings have been updated.' => 'The settings have been updated.', 
/** enable.php */ 
'djg_google_xml_sitemaps - plugin settings initialized.' => 'djg_google_xml_sitemaps - plugin settings initialized.', 
'djg_google_xml_sitemaps - unable to store plugin settings!' => 'djg_google_xml_sitemaps - unable to store plugin settings!', 
/** index.php */ 
'[djg] XML sitemaps' => '[djg] XML sitemaps', 
'Simple plugin to generate xml sitemap SEO compatible.' => 'Simple plugin to generate xml sitemap SEO compatible.', 
'Changefreq' => 'Changefreq', 
'always' => 'always', 
'hourly' => 'hourly', 
'daily' => 'daily', 
'weekly' => 'weekly', 
'monthly' => 'monthly', 
'yearly' => 'yearly', 
'never' => 'never', 
'Priority' => 'Priority', 
/** views\css_files.php */ 
'CSS files' => 'CSS files', 
'List css files from public/themes directory' => 'List css files from public/themes directory', 
'All available files are in use' => 'All available files are in use', 
'add selected' => 'add selected', 
'Files in use' => 'Files in use', 
'No files' => 'No files', 
'remove selected' => 'remove selected', 
'Copy and paste bellow code to your theme' => 'Copy and paste bellow code to your theme', 
'Show css content' => 'Show css content', 
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.', 
'Updated file list' => 'Updated file list', 
/** views\documentation.php */ 
'Documentation' => 'Documentation', 
/** views\settings.php */ 
'Settings' => 'Settings', 
'Header' => 'Header', 
'XML' => 'XML', 
'TXT' => 'TXT', 
'Choose header.' => 'Choose header.', 
'HOMEPAGE' => 'HOMEPAGE', 
'Yes' => 'Yes', 
'No' => 'No', 
'Add HOMEPAGE to xml tree.' => 'Add HOMEPAGE to xml tree.', 
'STATUS HIDDEN' => 'STATUS HIDDEN', 
'Add HIDDEN PAGES to xml tree.' => 'Add HIDDEN PAGES to xml tree.', 
'LOGIN REQUIRED' => 'LOGIN REQUIRED', 
'Add LOGIN REQUIRED PAGES to xml tree.' => 'Add LOGIN REQUIRED PAGES to xml tree.', 
'Default changefreq for pages.' => 'Default changefreq for pages.', 
'Default priority for pages.' => 'Default priority for pages.', 
'Cache' => 'Cache', 
'Set Yes if you want to caching sitemap file.' => 'Set Yes if you want to caching sitemap file.', 
'Auto clean cache after page update' => 'Auto clean cache after page update', 
'Robots.txt' => 'Robots.txt', 
'Contents of the robots.txt file.' => 'Contents of the robots.txt file.', 
'Virtual css path' => 'Virtual css path', 
'Save' => 'Save', 
'Show sitemap.xml file' => 'Show sitemap.xml file', 
'Show robots.txt file' => 'Show robots.txt file', 
/** views\sidebar.php */ 
'CSS' => 'CSS',
'Clear cache (:date)' => 'Clear cache (:date)',
'Documentation' => 'Documentation',
/** ver 1.1.4 */
'Virtual js path' => 'Virtual js path',
'JS' => 'JS',
'List js files from public/themes directory' => 'List js files from public/themes directory',
'Show js content' => 'Show js content'
);