<?php
/**
* English file for plugin djg_google_xml_sitemaps
*
* @package wolf
* @subpackage djg_google_xml_sitemaps
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast <djgprv@gmail.com>
*
**/
return array(
/** DjgGoogleXmlSitemapsController.php */ 
'Cache was cleared.' => 'Cache was cleared.', 
'The settings have been updated.' => 'The settings have been updated.', 
/** enable.php */ 
'djg_google_xml_sitemaps - plugin settings initialized.' => 'djg_google_xml_sitemaps - plugin settings initialized.', 
'djg_google_xml_sitemaps - unable to store plugin settings!' => 'djg_google_xml_sitemaps - unable to store plugin settings!', 
/** index.php */ 
'[djg] XML sitemaps' => '[djg] XML sitemaps', 
'Simple plugin to generate xml sitemap SEO compatible.' => 'Simple plugin to generate xml sitemap SEO compatible.', 
/** views\documentation.php */ 
'Djg Google Xml Sitemaps Documentation' => 'Djg Google Xml Sitemaps Documentation', 
'Sitemap adress is:' => 'Sitemap adress is:', 
'Read about sitemaps:' => 'Read about sitemaps:', 
'Your sitemap:' => 'Your sitemap:', 
/** views\settings.php */ 
'Settings' => 'Settings', 
'Header' => 'Header', 
'XML' => 'XML', 
'TXT' => 'TXT', 
'Choose header.' => 'Choose header.', 
'HOMEPAGE' => 'HOMEPAGE', 
'Yes' => 'Yes', 
'No' => 'No', 
'Add HOMEPAGE to xml tree.' => 'Add HOMEPAGE to xml tree.', 
'STATUS HIDDEN' => 'STATUS HIDDEN', 
'Add HIDDEN PAGES to xml tree.' => 'Add HIDDEN PAGES to xml tree.', 
'LOGIN REQUIRED' => 'LOGIN REQUIRED', 
'Add LOGIN REQUIRED PAGES to xml tree.' => 'Add LOGIN REQUIRED PAGES to xml tree.', 
'Changefreq' => 'Changefreq', 
'always' => 'always', 
'hourly' => 'hourly', 
'daily' => 'daily', 
'"weekly' => '"weekly', 
'monthly' => 'monthly', 
'yearly' => 'yearly', 
'never' => 'never', 
'Default changefreq for pages.' => 'Default changefreq for pages.', 
'Priority' => 'Priority', 
'Default priority for pages.' => 'Default priority for pages.', 
'Cache' => 'Cache', 
'Set Yes if you want to caching sitemap file.' => 'Set Yes if you want to caching sitemap file.', 
'Robots.txt' => 'Robots.txt', 
'Contents of the robots.txt file.' => 'Contents of the robots.txt file.', 
'Save' => 'Save', 
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.', 
/** views\sidebar.php */ 
'Documentation' => 'Documentation', 
);