<?php
/**
* English file for plugin djg_google_xml_sitemaps
*
* @package wolf
* @subpackage djg_google_xml_sitemaps
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast 
*
**/
return array(
/** DjgGoogleXmlSitemapsController.php */ 
'Cache was cleared.' => 'Pamięć podręczna została wyczyszczona.',
'The settings have been updated.' => 'Ustawienia zostały zaktualizowane.',
/** enable.php */ 
'djg_google_xml_sitemaps - plugin settings initialized.' => 'djg_google_xml_sitemaps - ustawienia wtyczki zainicjowany.',
'djg_google_xml_sitemaps - unable to store plugin settings!' => 'djg_google_xml_sitemaps - nie można zapisać ustawień wtyczki!',
/** index.php */ 
'[djg] XML sitemaps' => '[DJG] XML Sitemaps',
'Simple plugin to generate xml sitemap SEO compatible.' => 'Prosty plugin do generowania mapy strony XML SEO zgodne.',
/** views\documentation.php */ 
'Djg Google Xml Sitemaps Documentation' => 'DJG Google XML Sitemaps Dokumentacja',
'Sitemap adress is:' => 'Adres mapy to:',
'Read about sitemaps:' => 'Dowiedz się więcej:',
'Your sitemap:' => 'Mapa witryny:',
/** views\settings.php */ 
'Settings' => 'Ustawienia',
'Header' => 'Chodnikowiec',
'XML' => 'XML',
'TXT' => 'TXT',
'Choose header.' => 'Wybierz nagłówek.',
'HOMEPAGE' => 'STRONA GŁÓWNA',
'Yes' => 'Tak',
'No' => 'Nie',
'Add HOMEPAGE to xml tree.' => 'Dodaj Strona główna, aby drzewa XML.',
'STATUS HIDDEN' => 'STATUS HIDDEN',
'Add HIDDEN PAGES to xml tree.' => 'Dodaj ukryte strony do drzewa XML.',
'LOGIN REQUIRED' => 'Wymagany login',
'Add LOGIN REQUIRED PAGES to xml tree.' => 'Dodaj wymaga zalogowania strony do drzewa XML.',
'Changefreq' => 'Changefreq',
'always' => 'zawsze',
'hourly' => 'godzinowo',
'daily' => 'codziennie',
'weekly' => 'tygodniowo',
'monthly' => 'miesięcznie',
'yearly' => 'rocznie',
'never' => 'nigdy',
'Default changefreq for pages.' => 'Changefreq Domyślnie dla stron.',
'Priority' => 'Priorytet',
'Default priority for pages.' => 'Domyślnym priorytetem stron.',
'Cache' => 'Pamięć podręczna',
'Set Yes if you want to caching sitemap file.' => 'Wybierz Tak jeżeli chcesz używać pamięci podręcznej.',
'Robots.txt' => 'Robots.txt',
'Contents of the robots.txt file.' => 'Zawartość pliku robots.txt.',
'Save' => 'Zapisz',
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'Masz zmian tej strony. Jeśli nawigacja od tej strony bez wcześniejszego zapisywania danych, zmiany zostaną utracone.',
/** views\sidebar.php */ 
'Documentation' => 'Dokumentacja',
);