<?php
/**
* Polish file for plugin djg_google_xml_sitemaps
*
* @package wolf
* @subpackage djg_google_xml_sitemaps
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast 
*
**/
return array(
/** DjgGoogleXmlSitemapsController.php */ 
'Cache was cleared.' => 'Pamięć podręczna została wyczyszczona.',
'Successfully added file(s)' => 'Pomyślnie dodano plik(i)',
'Successfully removed file(s)' => 'Pomyślnie usunięto plik(i)',
'The settings have been updated.' => 'Ustawienia zostały zaktualizowane.',
/** enable.php */ 
'djg_google_xml_sitemaps - plugin settings initialized.' => 'djg_google_xml_sitemaps - ustawienia wtyczki zainicjowane.',
'djg_google_xml_sitemaps - unable to store plugin settings!' => 'djg_google_xml_sitemaps - Nie można zapisać ustawień wtyczki!',
/** index.php */ 
'[djg] XML sitemaps' => '[djg] XML sitemaps',
'Simple plugin to generate xml sitemap SEO compatible.' => 'Prosty plugin do generowania pliku sitemap kompatybilny z SEO.',
'Changefreq' => 'Changefreq',
'always' => 'zawsze',
'hourly' => 'po godzinach',
'daily' => 'codziennie',
'weekly' => 'tygodniowy',
'monthly' => 'miesięcznie',
'yearly' => 'rocznie',
'never' => 'nigdy',
'Priority' => 'Priority',
/** views\css_files.php */ 
'CSS files' => 'Pliki CSS',
'List css files from public/themes directory' => 'Lista plików css w katalogu public/themes',
'All available files are in use' => 'Wszystkie dostępne pliki są w użyciu',
'add selected' => 'dodaj zaznaczone',
'Files in use' => 'Pliki w użyciu',
'No files' => 'Brak plików',
'remove selected' => 'usuń wybrane',
'Copy and paste bellow code to your theme' => 'Skopiuj i wklej poniższy kod do szablonu',
'Show css content' => 'Pokaż zawartość css',
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'Wprowadziłeś zmiany. Jeśli przejdziesz do innej strony bez zapisywania zmiany zostaną utracone.',
'Updated file list' => 'Zaktualizowano listę plików',
/** views\documentation.php */ 
'Documentation' => 'Dokumentacja',
/** views\settings.php */ 
'Settings' => 'Ustawienia',
'Header' => 'Nagłówek',
'XML' => 'XML',
'TXT' => 'TXT',
'Choose header.' => 'Wybierz nagłówek.',
'HOMEPAGE' => 'STRONA GŁÓWNA',
'Yes' => 'Tak',
'No' => 'Nie',
'Add HOMEPAGE to xml tree.' => 'Dodaj GŁÓWNĄ STRONĘ do drzewa XML.',
'STATUS HIDDEN' => 'STATUS UKRYTE',
'Add HIDDEN PAGES to xml tree.' => 'Dodaj ukryte strony do drzewa XML.',
'LOGIN REQUIRED' => 'WYMAGA ZALOGOWANIA',
'Add LOGIN REQUIRED PAGES to xml tree.' => 'Dodaj strony wymagające logowania do drzewa XML.',
'Default changefreq for pages.' => 'Domyślny [changefreq] dla stron.',
'Default priority for pages.' => 'Domyślny [priorytet] dla stron.',
'Cache' => 'Cache',
'Set Yes if you want to caching sitemap file.' => 'Ustaw Tak, jeśli chcesz buforować plik sitemap.',
'Auto clean cache after page update' => 'Auto czyszczenie cache po aktualizacji strony',
'Robots.txt' => 'Robots.txt',
'Contents of the robots.txt file.' => 'Zawartość pliku robots.txt.',
'Virtual css path' => 'Wirtualna ścieżka css',
'Save' => 'Zapisz',
'Show sitemap.xml file' => 'Pokaż plik sitemap.xml',
'Show robots.txt file' => 'Pokaż plik robots.txt',
/** views\sidebar.php */ 
'CSS' => 'CSS',
'Clear cache (:date)' => 'Wyczyść cache (:date)',
'Documentation' => 'Dokumentacja',
);