<?php
/**
* English file for plugin djg_google_xml_sitemaps
*
* @package wolf
* @subpackage djg_google_xml_sitemaps
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast 
*
**/
return array(
/** DjgGoogleXmlSitemapsController.php */ 
'Cache was cleared.' => 'Pamięć podręczna została wyczyszczona.',
'Successfully added file(s)' => 'Został dodany plik (s)',
'Successfully removed file(s)' => 'Skutecznie usuwa plik (i)',
'The settings have been updated.' => 'Ustawienia zostały zaktualizowane.',
/** enable.php */ 
'djg_google_xml_sitemaps - plugin settings initialized.' => 'djg_google_xml_sitemaps - ustawienia wtyczki zainicjowany.',
'djg_google_xml_sitemaps - unable to store plugin settings!' => 'djg_google_xml_sitemaps - Nie można zapisać ustawień wtyczki!',
/** index.php */ 
'[djg] XML sitemaps' => '[XML Sitemaps djg]',
'Simple plugin to generate xml sitemap SEO compatible.' => 'Prosty plugin do generowania XML Sitemap SEO kompatybilny.',
'Changefreq' => 'Changefreq',
'always' => 'zawsze',
'hourly' => 'po godzinach',
'daily' => 'codziennie',
'weekly' => 'tygodniowy',
'monthly' => 'miesięcznie',
'yearly' => 'rocznie',
'never' => 'nigdy',
'Priority' => 'Priorytet',
/** views\css_files.php */ 
'CSS files' => 'Pliki CSS',
'List css files from public/themes directory' => 'Lista plików z katalogu css / themes publicznych',
'All available files are in use' => 'Wszystkie dostępne pliki są w użyciu',
'add selected' => 'dodać wybrany',
'Files in use' => 'Pliki w użyciu',
'No files' => 'Brak plików',
'remove selected' => 'usunąć wybrany',
'Show css content' => 'Zawartość Pokaż css',
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'Zmodyfikowaniu tej strony.  Jeżeli nawigacja z dala od tej strony bez wcześniejszego zapisywania danych, zmiany zostaną utracone.',
'Updated file list' => 'Aktualizowana lista plików',
/** views\documentation.php */ 
'Documentation' => 'Dokumentacja',
/** views\settings.php */ 
'Settings' => 'Ustawienia',
'Header' => 'Chodnikowiec',
'XML' => 'XML',
'TXT' => 'TXT',
'Choose header.' => 'Wybierz nagłówek.',
'HOMEPAGE' => 'GŁÓWNĄ',
'Yes' => 'Tak',
'No' => 'Nie',
'Add HOMEPAGE to xml tree.' => 'Dodaj strony kieruj do drzewa XML.',
'STATUS HIDDEN' => 'STATUS UKRYTE',
'Add HIDDEN PAGES to xml tree.' => 'Dodaj ukryte strony do drzewa XML.',
'LOGIN REQUIRED' => 'Zalogowanych',
'Add LOGIN REQUIRED PAGES to xml tree.' => 'Dodaj zalogowanych strony do drzewa XML.',
'Default changefreq for pages.' => 'Domyślnie changefreq dla stron.',
'Default priority for pages.' => 'Domyślnym priorytetem dla stron.',
'Cache' => 'Cache',
'Set Yes if you want to caching sitemap file.' => 'Ustaw Tak, jeśli chcesz buforowanie sitemap plik.',
'Auto clean cache after page update' => 'Auto czyste cache po aktualizacji strony',
'Robots.txt' => 'Robots.txt',
'Contents of the robots.txt file.' => 'Zawartość pliku robots.txt.',
'Virtual css path' => 'Wirtualna ścieżka css',
'Save' => 'Oszczędzać',
'Show sitemap.xml file' => 'Pokaż plik sitemap.xml',
'Show robots.txt file' => 'Pokaż plik robots.txt',
/** views\sidebar.php */ 
'CSS' => 'CSS',
'Clear cache (:date)' => 'USUN cache (Data)',
'Documentation' => 'DOKUMENTACJA',
);