<?php
/**
* English file for plugin djg_google_xml_sitemaps
*
* @package wolf
* @subpackage djg_google_xml_sitemaps
*
* @generated by djg_i18n_generator WolfCMS plugin - Michał Uchnast 
*
**/
return array(
/** DjgGoogleXmlSitemapsController.php */ 
'Cache was cleared.' => 'Кэш был очищен.',
'Successfully added file(s)' => 'Успешно добавлен файл (ы)',
'Successfully removed file(s)' => 'Успешно удалены файл (ы)',
'The settings have been updated.' => 'Настройки были обновлены.',
/** enable.php */ 
'djg_google_xml_sitemaps - plugin settings initialized.' => 'djg_google_xml_sitemaps - настройки плагина инициализированы.',
'djg_google_xml_sitemaps - unable to store plugin settings!' => 'djg_google_xml_sitemaps - не в состоянии хранить плагинов настройки!',
/** index.php */ 
'[djg] XML sitemaps' => '[DJG] XML карты сайта',
'Simple plugin to generate xml sitemap SEO compatible.' => 'Простой плагин для генерации XML Sitemap SEO совместимый.',
'Changefreq' => 'Changefreq',
'always' => 'всегда',
'hourly' => 'ежечасно',
'daily' => 'ежедневно',
'weekly' => 'еженедельно',
'monthly' => 'ежемесячно',
'yearly' => 'годовой',
'never' => 'никогда',
'Priority' => 'Приоритет',
/** views\css_files.php */ 
'CSS files' => 'CSS-файлы',
'List css files from public/themes directory' => 'Список CSS файлы из каталога с общественностью / Темы',
'All available files are in use' => 'Все имеющиеся файлы используются',
'add selected' => 'добавить выбран',
'Files in use' => 'Файлы в использовании',
'No files' => 'Нет файлов',
'remove selected' => 'удалить выбран',
'Show css content' => 'Содержание Показать CSS',
'You have modified this page.  If you navigate away from this page without first saving your data, the changes will be lost.' => 'Вы изменили эту страницу.  Если вы уйдете с этой страницы, не сохранив данные, изменения будут потеряны.',
'Updated file list' => 'Обновлен список файлов',
/** views\documentation.php */ 
'Documentation' => 'Документация',
/** views\settings.php */ 
'Settings' => 'Настройки',
'Header' => 'Заголовок',
'XML' => 'XML',
'TXT' => 'TXT',
'Choose header.' => 'Выберите заголовок.',
'HOMEPAGE' => 'ГЛАВНАЯ',
'Yes' => 'Да',
'No' => 'Нет',
'Add HOMEPAGE to xml tree.' => 'Добавить веб-странице XML-дерево.',
'STATUS HIDDEN' => 'СТАТУС HIDDEN',
'Add HIDDEN PAGES to xml tree.' => 'Добавить скрытых страниц в XML-дерево.',
'LOGIN REQUIRED' => 'Требуется авторизация',
'Add LOGIN REQUIRED PAGES to xml tree.' => 'Добавить требуется авторизация СТРАНИЦЫ, чтобы XML-дерево.',
'Default changefreq for pages.' => 'По умолчанию changefreq для страниц.',
'Default priority for pages.' => 'По умолчанию приоритет для страниц.',
'Cache' => 'Кэш',
'Set Yes if you want to caching sitemap file.' => 'Установить Да, если вы хотите кэширования карта сайта файл.',
'Auto clean cache after page update' => 'Авто чистым кэш-память после обновления страницы',
'Robots.txt' => 'Robots.txt',
'Contents of the robots.txt file.' => 'Содержание файла robots.txt.',
'Virtual css path' => 'Виртуальный путь CSS',
'Save' => 'Экономить',
'Show sitemap.xml file' => 'Показать sitemap.xml файл',
'Show robots.txt file' => 'Показать файл robots.txt',
/** views\sidebar.php */ 
'CSS' => 'CSS',
'Clear cache (:date)' => 'Усуньского кэш (: дата)',
'Documentation' => 'Dokumentacja',
);